name: 'Continuous Integration'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: 'CI: Check quality'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change directory to pmy
        run: cd pmy

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npm run type:check

      - name: Check ESLint
        run: npm run lint
