name: 'CI: TypeScript & ESLint Check'

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main  # or specify your default branch here

jobs:
  quality:
    name: 'CI: Check quality'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

       # Set up Node.js 20
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd pmy
          npm install

      # Step 4: TypeScript Check (tsc)
      - name: Run TypeScript
        run: |
          cd pmy
          npm run build
        continue-on-error: true  # Keep the workflow running even if TypeScript fails

      # Step 5: ESLint Check
      - name: Run ESLint
        run: |
          cd pmy
          npm run lint
        continue-on-error: true  # Keep the workflow running even if ESLint fails
